so the backup will rerun

diff --git a/.github/workflows/database-restore.yml b/.github/workflows/database-restore.yml
--- a/.github/workflows/database-restore.yml
+++ b/.github/workflows/database-restore.yml
@@ -53,7 +53,7 @@ jobs:
       name: ${{ inputs.environment || 'production' }}
     env:
       DEPLOY_ENV: ${{ inputs.environment || 'production'  }}
-      BACKUP_FILE: ${{ inputs.backup-file || 'schedule'  }}
+      BACKUP_FILE: ${{ 'schedule'  }}
     services:
       postgres:
         image: postgis/postgis:17-3.6-alpine
@@ -89,97 +89,97 @@ jobs:
           fi
           echo "BACKUP_FILE=${BACKUP_FILE}" >> $GITHUB_ENV
 
-      - name: Azure Login
-        if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
-        uses: azure/login@v3
-        with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      # - name: Azure Login
+      #   if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
+      #   uses: azure/login@v3
+      #   with:
+      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Set Connection String
-        if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
-        shell: bash
-        run: |
-          STORAGE_CONN_STR=$(az storage account show-connection-string -g ${{ env.RESOURCE_GROUP_NAME }} -n ${{ env.STORAGE_ACCOUNT_NAME }} --query 'connectionString')
-          echo "::add-mask::$STORAGE_CONN_STR"
-          echo "AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONN_STR" >> $GITHUB_ENV
+      # - name: Set Connection String
+      #   if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
+      #   shell: bash
+      #   run: |
+      #     STORAGE_CONN_STR=$(az storage account show-connection-string -g ${{ env.RESOURCE_GROUP_NAME }} -n ${{ env.STORAGE_ACCOUNT_NAME }} --query 'connectionString')
+      #     echo "::add-mask::$STORAGE_CONN_STR"
+      #     echo "AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONN_STR" >> $GITHUB_ENV
 
-      - name: Download existing backup from Azure Storage
-        if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
-        shell: bash
-        run: |
-          az storage blob download \
-            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
-            --container-name database-backup \
-            --name "${{ env.BACKUP_FILE }}.sql.gz" \
-            --file "${{ env.BACKUP_FILE }}.sql.gz" \
-            --output none
+      # - name: Download existing backup from Azure Storage
+      #   if: github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true'
+      #   shell: bash
+      #   run: |
+      #     az storage blob download \
+      #       --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
+      #       --container-name database-backup \
+      #       --name "${{ env.BACKUP_FILE }}.sql.gz" \
+      #       --file "${{ env.BACKUP_FILE }}.sql.gz" \
+      #       --output none
 
-      - name: Backup ${{ env.DEPLOY_ENV }} postgres
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP != 'true')
-        uses: DFE-Digital/github-actions/backup-postgres@master
-        with:
-          storage-account: ${{ env.STORAGE_ACCOUNT_NAME }}
-          resource-group: ${{ env.RESOURCE_GROUP_NAME }}
-          app-name: ${{ env.SERVICE_NAME }}-${{ env.DEPLOY_ENV }}
-          namespace: ${{ env.NAMESPACE }}
-          cluster: ${{ env.CLUSTER }}
-          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          backup-file: ${{ env.BACKUP_FILE }}.sql
-          db-server-name: ${{ inputs.db-server }}
-          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
-          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
+      # - name: Backup ${{ env.DEPLOY_ENV }} postgres
+      #   #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP != 'true')
+      #   uses: DFE-Digital/github-actions/backup-postgres@master
+      #   with:
+      #     storage-account: ${{ env.STORAGE_ACCOUNT_NAME }}
+      #     resource-group: ${{ env.RESOURCE_GROUP_NAME }}
+      #     app-name: ${{ env.SERVICE_NAME }}-${{ env.DEPLOY_ENV }}
+      #     namespace: ${{ env.NAMESPACE }}
+      #     cluster: ${{ env.CLUSTER }}
+      #     azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      #     azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+      #     azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      #     backup-file: ${{ env.BACKUP_FILE }}.sql
+      #     db-server-name: ${{ inputs.db-server }}
+      #     teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
+      #     service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
 
       - name: Set env variable
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
+        #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
         run: echo "SANITISED_FILE_NAME=publish_sanitised_$(date +"%F")" >> $GITHUB_ENV
 
-      - name: Sanitise the Database backup
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
-        run: |
-          echo "::group::Restore backup to intermediate database"
-          createdb ${DATABASE_NAME} && gzip -d --to-stdout ${{ env.BACKUP_FILE }}.sql.gz | psql -d ${DATABASE_NAME}
-          echo "::endgroup::"
+      # - name: Sanitise the Database backup
+      #   #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
+      #   run: |
+      #     echo "::group::Restore backup to intermediate database"
+      #     createdb ${DATABASE_NAME} && gzip -d --to-stdout ${{ env.BACKUP_FILE }}.sql.gz | psql -d ${DATABASE_NAME}
+      #     echo "::endgroup::"
 
-          echo "::group::Clear user data"
-          psql -d ${DATABASE_NAME} -v ON_ERROR_STOP=1 -f db/scripts/sanitise.sql
-            if [ $? -ne 0 ]; then
-              echo "db/scripts/sanitise.sql failed" >&2
-              exit 1
-            fi
-          echo "::endgroup::"
+      #     echo "::group::Clear user data"
+      #     psql -d ${DATABASE_NAME} -v ON_ERROR_STOP=1 -f db/scripts/sanitise.sql
+      #       if [ $? -ne 0 ]; then
+      #         echo "db/scripts/sanitise.sql failed" >&2
+      #         exit 1
+      #       fi
+      #     echo "::endgroup::"
 
-          echo "::group::Integration setup"
-          psql -d ${DATABASE_NAME} -v ON_ERROR_STOP=1 -f db/scripts/integration_setup.sql
-            if [ $? -ne 0 ]; then
-              echo "db/scripts/integration_setup.sql failed" >&2
-              exit 1
-            fi
-          echo "::endgroup::"
+      #     echo "::group::Integration setup"
+      #     psql -d ${DATABASE_NAME} -v ON_ERROR_STOP=1 -f db/scripts/integration_setup.sql
+      #       if [ $? -ne 0 ]; then
+      #         echo "db/scripts/integration_setup.sql failed" >&2
+      #         exit 1
+      #       fi
+      #     echo "::endgroup::"
 
-          echo "::debug::Remove ${{ env.BACKUP_FILE }}.sql.gz"
-          rm ${{ env.BACKUP_FILE }}.sql.gz
+      #     echo "::debug::Remove ${{ env.BACKUP_FILE }}.sql.gz"
+      #     rm ${{ env.BACKUP_FILE }}.sql.gz
 
-          echo "::group::Backup Sanitised Database"
-          pg_dump --compress=1 --encoding utf8 --clean --no-owner --if-exists -d ${DATABASE_NAME} -f ${SANITISED_FILE_NAME}.sql.gz
-          echo "::endgroup::"
-        env:
-          DATABASE_NAME: teacher_training_api
-          PGUSER: postgres
-          PGPASSWORD: postgres
-          PGHOST: localhost
-          PGPORT: 5432
+      #     echo "::group::Backup Sanitised Database"
+      #     pg_dump --compress=1 --encoding utf8 --clean --no-owner --if-exists -d ${DATABASE_NAME} -f ${SANITISED_FILE_NAME}.sql.gz
+      #     echo "::endgroup::"
+      #   env:
+      #     DATABASE_NAME: teacher_training_api
+      #     PGUSER: postgres
+      #     PGPASSWORD: postgres
+      #     PGHOST: localhost
+      #     PGPORT: 5432
 
-      - name: Upload Backup to Azure Storage
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
-        run: |
-          az storage blob upload --container-name database-backup \
-          --file ${SANITISED_FILE_NAME}.sql.gz --name ${SANITISED_FILE_NAME}.sql.gz --overwrite \
-          --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING_SANITISED }}'
-          rm ${SANITISED_FILE_NAME}.sql.gz
+      # - name: Upload Backup to Azure Storage
+      #   #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true')
+      #   run: |
+      #     az storage blob upload --container-name database-backup \
+      #     --file ${SANITISED_FILE_NAME}.sql.gz --name ${SANITISED_FILE_NAME}.sql.gz --overwrite \
+      #     --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING_SANITISED }}'
+      #     rm ${SANITISED_FILE_NAME}.sql.gz
 
   restore:
     needs: [backup]
@@ -194,11 +194,11 @@ jobs:
         environment: [qa, staging]
     steps:
       - name: Checkout
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true') && env.SKIP_RESTORE == 'false'
+        #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true') && env.SKIP_RESTORE == 'false'
         uses: actions/checkout@v7
 
       - name: Restore database
-        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true') && env.SKIP_RESTORE == 'false'
+        #if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && env.SKIP_BACKUP == 'true') && env.SKIP_RESTORE == 'false'
         id: restore
         uses: ./.github/actions/restore/
         with:
